---
LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.macTest
PRODUCT_NAME: "$(TARGET_NAME)"
SWIFT_VERSION: '3.0'
