---
version: 2.0.0
configurations:
  debug:
  release:
targets:
  tvOSTest:
    sources: tvOSTest
    i18n-resources: tvOSTest/lproj
    excludes:
      files:
      - "**/*.md"
    references:
    - sdkroot:UIKit.framework
    platform: tv
    type: ":application"
    configuration:
      ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
      ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME: LaunchImage
      INFOPLIST_FILE: tvOSTest/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.tvOSTest